# A minimal config file for Helix
# By @michalspano

theme = "nord-transparent" # my custom theme (with transparent background)

[editor]
  line-number = "relative"
  mouse = false
  shell = ["zsh", "-c"]

[keys.normal]
  C-p = ["move_line_up", "scroll_up"]
  C-n = ["move_line_down", "scroll_down"]
  esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
  insert = "bar"
  normal = "block"
  select = "block"

[editor.file-picker]
  hidden = false
